// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access.sql

package storedb

import (
	"context"
)

const deleteAccess = `-- name: DeleteAccess :exec
DELETE FROM access
`

func (q *Queries) DeleteAccess(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAccess)
	return err
}

const insertAccess = `-- name: InsertAccess :exec
INSERT INTO access (kind, cidr) VALUES (?, ?)
`

type InsertAccessParams struct {
	Kind string
	Cidr string
}

func (q *Queries) InsertAccess(ctx context.Context, arg InsertAccessParams) error {
	_, err := q.db.ExecContext(ctx, insertAccess, arg.Kind, arg.Cidr)
	return err
}

const listAccess = `-- name: ListAccess :many
SELECT kind, cidr FROM access ORDER BY kind, cidr
`

func (q *Queries) ListAccess(ctx context.Context) ([]Access, error) {
	rows, err := q.db.QueryContext(ctx, listAccess)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Access
	for rows.Next() {
		var i Access
		if err := rows.Scan(&i.Kind, &i.Cidr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
