// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package storedb

import (
	"context"
)

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients WHERE name = ?
`

func (q *Queries) DeleteClient(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteClient, name)
	return err
}

const deleteClientAddress = `-- name: DeleteClientAddress :exec
DELETE FROM client_addresses WHERE address = ?
`

func (q *Queries) DeleteClientAddress(ctx context.Context, address string) error {
	_, err := q.db.ExecContext(ctx, deleteClientAddress, address)
	return err
}

const deleteClientAddressesForClient = `-- name: DeleteClientAddressesForClient :exec
DELETE FROM client_addresses WHERE client = ?
`

func (q *Queries) DeleteClientAddressesForClient(ctx context.Context, client string) error {
	_, err := q.db.ExecContext(ctx, deleteClientAddressesForClient, client)
	return err
}

const deleteClientMAC = `-- name: DeleteClientMAC :exec
DELETE FROM client_macs WHERE mac = ?
`

func (q *Queries) DeleteClientMAC(ctx context.Context, mac string) error {
	_, err := q.db.ExecContext(ctx, deleteClientMAC, mac)
	return err
}

const deleteClientMACsForClient = `-- name: DeleteClientMACsForClient :exec
DELETE FROM client_macs WHERE client = ?
`

func (q *Queries) DeleteClientMACsForClient(ctx context.Context, client string) error {
	_, err := q.db.ExecContext(ctx, deleteClientMACsForClient, client)
	return err
}

const deleteClientPrefix = `-- name: DeleteClientPrefix :exec
DELETE FROM client_prefixes WHERE prefix = ?
`

func (q *Queries) DeleteClientPrefix(ctx context.Context, prefix string) error {
	_, err := q.db.ExecContext(ctx, deleteClientPrefix, prefix)
	return err
}

const deleteClientPrefixesForClient = `-- name: DeleteClientPrefixesForClient :exec
DELETE FROM client_prefixes WHERE client = ?
`

func (q *Queries) DeleteClientPrefixesForClient(ctx context.Context, client string) error {
	_, err := q.db.ExecContext(ctx, deleteClientPrefixesForClient, client)
	return err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles WHERE name = ?
`

func (q *Queries) DeleteProfile(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteProfile, name)
	return err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listClientAddresses = `-- name: ListClientAddresses :many
SELECT address, client FROM client_addresses ORDER BY address
`

func (q *Queries) ListClientAddresses(ctx context.Context) ([]ClientAddress, error) {
	rows, err := q.db.QueryContext(ctx, listClientAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientAddress
	for rows.Next() {
		var i ClientAddress
		if err := rows.Scan(&i.Address, &i.Client); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientMACs = `-- name: ListClientMACs :many
SELECT mac, client FROM client_macs ORDER BY mac
`

func (q *Queries) ListClientMACs(ctx context.Context) ([]ClientMac, error) {
	rows, err := q.db.QueryContext(ctx, listClientMACs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientMac
	for rows.Next() {
		var i ClientMac
		if err := rows.Scan(&i.Mac, &i.Client); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientPrefixes = `-- name: ListClientPrefixes :many
SELECT prefix, client FROM client_prefixes ORDER BY prefix
`

func (q *Queries) ListClientPrefixes(ctx context.Context) ([]ClientPrefix, error) {
	rows, err := q.db.QueryContext(ctx, listClientPrefixes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientPrefix
	for rows.Next() {
		var i ClientPrefix
		if err := rows.Scan(&i.Prefix, &i.Client); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClients = `-- name: ListClients :many
SELECT name, profile, notes FROM clients ORDER BY name
`

func (q *Queries) ListClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(&i.Name, &i.Profile, &i.Notes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfiles = `-- name: ListProfiles :many
SELECT name, extends, mode, custom FROM profiles ORDER BY name
`

func (q *Queries) ListProfiles(ctx context.Context) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.Name,
			&i.Extends,
			&i.Mode,
			&i.Custom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSetting = `-- name: SetSetting :exec
INSERT INTO settings (key, value) VALUES (?, ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

type SetSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) error {
	_, err := q.db.ExecContext(ctx, setSetting, arg.Key, arg.Value)
	return err
}

const upsertClient = `-- name: UpsertClient :exec
INSERT INTO clients (name, profile, notes) VALUES (?, ?, ?)
ON CONFLICT (name) DO UPDATE SET profile = excluded.profile, notes = excluded.notes
`

type UpsertClientParams struct {
	Name    string
	Profile string
	Notes   string
}

func (q *Queries) UpsertClient(ctx context.Context, arg UpsertClientParams) error {
	_, err := q.db.ExecContext(ctx, upsertClient, arg.Name, arg.Profile, arg.Notes)
	return err
}

const upsertClientAddress = `-- name: UpsertClientAddress :exec
INSERT INTO client_addresses (address, client) VALUES (?, ?)
ON CONFLICT (address) DO UPDATE SET client = excluded.client
`

type UpsertClientAddressParams struct {
	Address string
	Client  string
}

func (q *Queries) UpsertClientAddress(ctx context.Context, arg UpsertClientAddressParams) error {
	_, err := q.db.ExecContext(ctx, upsertClientAddress, arg.Address, arg.Client)
	return err
}

const upsertClientMAC = `-- name: UpsertClientMAC :exec
INSERT INTO client_macs (mac, client) VALUES (?, ?)
ON CONFLICT (mac) DO UPDATE SET client = excluded.client
`

type UpsertClientMACParams struct {
	Mac    string
	Client string
}

func (q *Queries) UpsertClientMAC(ctx context.Context, arg UpsertClientMACParams) error {
	_, err := q.db.ExecContext(ctx, upsertClientMAC, arg.Mac, arg.Client)
	return err
}

const upsertClientPrefix = `-- name: UpsertClientPrefix :exec
INSERT INTO client_prefixes (prefix, client) VALUES (?, ?)
ON CONFLICT (prefix) DO UPDATE SET client = excluded.client
`

type UpsertClientPrefixParams struct {
	Prefix string
	Client string
}

func (q *Queries) UpsertClientPrefix(ctx context.Context, arg UpsertClientPrefixParams) error {
	_, err := q.db.ExecContext(ctx, upsertClientPrefix, arg.Prefix, arg.Client)
	return err
}

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO profiles (name, extends, mode, custom) VALUES (?, ?, ?, ?)
ON CONFLICT (name) DO UPDATE SET
    extends = excluded.extends,
    mode = excluded.mode,
    custom = excluded.custom
`

type UpsertProfileParams struct {
	Name    string
	Extends *string
	Mode    *string
	Custom  *string
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) error {
	_, err := q.db.ExecContext(ctx, upsertProfile,
		arg.Name,
		arg.Extends,
		arg.Mode,
		arg.Custom,
	)
	return err
}
