// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dhcp.sql

package storedb

import (
	"context"
)

const deleteDiscovery = `-- name: DeleteDiscovery :exec
DELETE FROM discoveries WHERE mac = ?
`

func (q *Queries) DeleteDiscovery(ctx context.Context, mac string) error {
	_, err := q.db.ExecContext(ctx, deleteDiscovery, mac)
	return err
}

const deleteExpiredLeases = `-- name: DeleteExpiredLeases :execrows
DELETE FROM leases WHERE expires <= ?
`

func (q *Queries) DeleteExpiredLeases(ctx context.Context, expires int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredLeases, expires)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteLease = `-- name: DeleteLease :exec
DELETE FROM leases WHERE address = ?
`

func (q *Queries) DeleteLease(ctx context.Context, address string) error {
	_, err := q.db.ExecContext(ctx, deleteLease, address)
	return err
}

const listDiscoveries = `-- name: ListDiscoveries :many
SELECT mac, address, hostname, first, last FROM discoveries ORDER BY last DESC
`

func (q *Queries) ListDiscoveries(ctx context.Context) ([]Discovery, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Discovery
	for rows.Next() {
		var i Discovery
		if err := rows.Scan(
			&i.Mac,
			&i.Address,
			&i.Hostname,
			&i.First,
			&i.Last,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeases = `-- name: ListLeases :many
SELECT address, mac, client, hostname, expires FROM leases ORDER BY address
`

func (q *Queries) ListLeases(ctx context.Context) ([]Lease, error) {
	rows, err := q.db.QueryContext(ctx, listLeases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lease
	for rows.Next() {
		var i Lease
		if err := rows.Scan(
			&i.Address,
			&i.Mac,
			&i.Client,
			&i.Hostname,
			&i.Expires,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDiscovery = `-- name: UpsertDiscovery :exec
INSERT INTO discoveries (mac, address, hostname, first, last) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (mac) DO UPDATE SET
    address = excluded.address,
    hostname = excluded.hostname,
    last = excluded.last
`

type UpsertDiscoveryParams struct {
	Mac      string
	Address  string
	Hostname string
	First    int64
	Last     int64
}

func (q *Queries) UpsertDiscovery(ctx context.Context, arg UpsertDiscoveryParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscovery,
		arg.Mac,
		arg.Address,
		arg.Hostname,
		arg.First,
		arg.Last,
	)
	return err
}

const upsertLease = `-- name: UpsertLease :exec
INSERT INTO leases (address, mac, client, hostname, expires) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (address) DO UPDATE SET
    mac = excluded.mac,
    client = excluded.client,
    hostname = excluded.hostname,
    expires = excluded.expires
`

type UpsertLeaseParams struct {
	Address  string
	Mac      string
	Client   *string
	Hostname string
	Expires  int64
}

func (q *Queries) UpsertLease(ctx context.Context, arg UpsertLeaseParams) error {
	_, err := q.db.ExecContext(ctx, upsertLease,
		arg.Address,
		arg.Mac,
		arg.Client,
		arg.Hostname,
		arg.Expires,
	)
	return err
}
