// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: focus.sql

package storedb

import (
	"context"
)

const deleteFocusWindow = `-- name: DeleteFocusWindow :exec
DELETE FROM focus_windows WHERE name = ?
`

func (q *Queries) DeleteFocusWindow(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteFocusWindow, name)
	return err
}

const focusWindowByName = `-- name: FocusWindowByName :one
SELECT id, name, schedule, clients, services
FROM focus_windows WHERE name = ?
`

func (q *Queries) FocusWindowByName(ctx context.Context, name string) (FocusWindow, error) {
	row := q.db.QueryRowContext(ctx, focusWindowByName, name)
	var i FocusWindow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Schedule,
		&i.Clients,
		&i.Services,
	)
	return i, err
}

const listFocusWindows = `-- name: ListFocusWindows :many
SELECT id, name, schedule, clients, services
FROM focus_windows ORDER BY name
`

func (q *Queries) ListFocusWindows(ctx context.Context) ([]FocusWindow, error) {
	rows, err := q.db.QueryContext(ctx, listFocusWindows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FocusWindow
	for rows.Next() {
		var i FocusWindow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Schedule,
			&i.Clients,
			&i.Services,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveFocusWindow = `-- name: SaveFocusWindow :one
INSERT INTO focus_windows (name, schedule, clients, services)
VALUES (?, ?, ?, ?)
ON CONFLICT (name) DO UPDATE SET
    schedule = excluded.schedule,
    clients  = excluded.clients,
    services = excluded.services
RETURNING id
`

type SaveFocusWindowParams struct {
	Name     string
	Schedule string
	Clients  string
	Services string
}

func (q *Queries) SaveFocusWindow(ctx context.Context, arg SaveFocusWindowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, saveFocusWindow,
		arg.Name,
		arg.Schedule,
		arg.Clients,
		arg.Services,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
