// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storedb

type Client struct {
	Name    string
	Profile string
	Notes   string
}

type ClientAddress struct {
	Address string
	Client  string
}

type ClientPrefix struct {
	Prefix string
	Client string
}

type Profile struct {
	Name    string
	Extends *string
	Mode    *string
	Custom  *string
}

type Setting struct {
	Key   string
	Value string
}

type Source struct {
	Name      string
	Url       string
	Format    string
	Enabled   int64
	Etag      string
	LastFetch int64
	LastError string
	RuleCount int64
	Body      []byte
}
