// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storedb

type Access struct {
	Kind string
	Cidr string
}

type Client struct {
	Name    string
	Profile string
	Notes   string
}

type ClientAddress struct {
	Address string
	Client  string
}

type ClientMac struct {
	Mac    string
	Client string
}

type ClientPrefix struct {
	Prefix string
	Client string
}

type ClientService struct {
	Client  string
	Service string
}

type Discovery struct {
	Mac      string
	Address  string
	Hostname string
	First    int64
	Last     int64
}

type FocusWindow struct {
	ID       int64
	Name     string
	Schedule string
	Clients  string
	Services string
}

type Lease struct {
	Address  string
	Mac      string
	Client   *string
	Hostname string
	Expires  int64
}

type Profile struct {
	Name    string
	Extends *string
	Mode    *string
	Custom  *string
}

type ProfileSafesearch struct {
	Profile string
	Engine  string
}

type ProfileService struct {
	Profile string
	Service string
}

type Query struct {
	ID      int64
	Time    int64
	Client  string
	Name    string
	Type    string
	Verdict string
	Rule    string
	Threat  string
}

type Rewrite struct {
	Domain string
	Target string
}

type Route struct {
	ID       int64
	Domain   string
	Client   string
	Upstream string
}

type Rule struct {
	ID       int64
	Domain   string
	Kind     string
	Action   string
	Notes    string
	Created  int64
	Schedule string
	Client   string
}

type Schedule struct {
	Name     string
	Priority int64
	Windows  string
}

type Service struct {
	ID        string
	Name      string
	GroupName string
	Rules     string
	FetchedAt int64
	IconSvg   string
}

type Setting struct {
	Key   string
	Value string
}

type Source struct {
	Name           string
	Url            string
	Format         string
	Enabled        int64
	Etag           string
	LastFetch      int64
	LastError      string
	RuleCount      int64
	Body           []byte
	Skipped        int64
	Failures       int64
	RefreshSeconds int64
}

type ThreatDomain struct {
	Domain string
	Kind   string
	Feed   string
}

type ThreatFeed struct {
	Name    string
	Url     string
	Enabled int64
}

type ThreatFinding struct {
	ID       int64
	Time     int64
	Client   string
	Kind     string
	Summary  string
	Evidence string
}

type Upstream struct {
	Name    string
	Url     string
	Enabled int64
	Backup  int64
}
