// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: observed.sql

package storedb

import (
	"context"
)

const observedClients = `-- name: ObservedClients :many
SELECT q.client AS client,
       COUNT(*) AS queries,
       CAST(MAX(q.time) AS INTEGER) AS last_seen,
       EXISTS (SELECT 1 FROM client_addresses a WHERE a.address = q.client) AS claimed
FROM queries q
WHERE q.time >= ?
GROUP BY q.client
ORDER BY queries DESC, client ASC
LIMIT ?
`

type ObservedClientsParams struct {
	Time  int64
	Limit int64
}

type ObservedClientsRow struct {
	Client   string
	Queries  int64
	LastSeen int64
	Claimed  int64
}

func (q *Queries) ObservedClients(ctx context.Context, arg ObservedClientsParams) ([]ObservedClientsRow, error) {
	rows, err := q.db.QueryContext(ctx, observedClients, arg.Time, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ObservedClientsRow
	for rows.Next() {
		var i ObservedClientsRow
		if err := rows.Scan(
			&i.Client,
			&i.Queries,
			&i.LastSeen,
			&i.Claimed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
