// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package storedb

import (
	"context"
	"database/sql"
)

const insertQueries = `-- name: InsertQueries :execresult
INSERT INTO queries (time, client, name, type, verdict, rule)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertQueriesParams struct {
	Time    int64
	Client  string
	Name    string
	Type    string
	Verdict string
	Rule    string
}

func (q *Queries) InsertQueries(ctx context.Context, arg InsertQueriesParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertQueries,
		arg.Time,
		arg.Client,
		arg.Name,
		arg.Type,
		arg.Verdict,
		arg.Rule,
	)
}

const listQueries = `-- name: ListQueries :many
SELECT id, time, client, name, type, verdict, rule
FROM queries
WHERE (?1 = '' OR client = ?1)
  AND (?2 = '' OR verdict = ?2)
  AND (?3 = '' OR name = ?3 OR name LIKE ?4)
ORDER BY id DESC
LIMIT ?5
`

type ListQueriesParams struct {
	Client     interface{}
	Verdict    interface{}
	ExactName  interface{}
	SuffixName string
	Limit      int64
}

func (q *Queries) ListQueries(ctx context.Context, arg ListQueriesParams) ([]Query, error) {
	rows, err := q.db.QueryContext(ctx, listQueries,
		arg.Client,
		arg.Verdict,
		arg.ExactName,
		arg.SuffixName,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Query
	for rows.Next() {
		var i Query
		if err := rows.Scan(
			&i.ID,
			&i.Time,
			&i.Client,
			&i.Name,
			&i.Type,
			&i.Verdict,
			&i.Rule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trimQueries = `-- name: TrimQueries :exec
DELETE FROM queries WHERE id <= (
    SELECT id FROM queries ORDER BY id DESC LIMIT 1 OFFSET ?1
)
`

func (q *Queries) TrimQueries(ctx context.Context, keep int64) error {
	_, err := q.db.ExecContext(ctx, trimQueries, keep)
	return err
}
