// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reset.sql

package storedb

import (
	"context"
	"database/sql"
)

const wipeAccess = `-- name: WipeAccess :execresult
DELETE FROM access
`

func (q *Queries) WipeAccess(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, wipeAccess)
}

const wipeClientRoutes = `-- name: WipeClientRoutes :execresult
DELETE FROM routes WHERE client <> ''
`

func (q *Queries) WipeClientRoutes(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, wipeClientRoutes)
}

const wipeClients = `-- name: WipeClients :execresult
DELETE FROM clients
`

func (q *Queries) WipeClients(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, wipeClients)
}

const wipeDiscoveries = `-- name: WipeDiscoveries :execresult
DELETE FROM discoveries
`

func (q *Queries) WipeDiscoveries(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, wipeDiscoveries)
}

const wipeQueries = `-- name: WipeQueries :execresult
DELETE FROM queries
`

func (q *Queries) WipeQueries(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, wipeQueries)
}

const wipeServiceWindows = `-- name: WipeServiceWindows :execresult
DELETE FROM service_windows
`

func (q *Queries) WipeServiceWindows(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, wipeServiceWindows)
}

const wipeServices = `-- name: WipeServices :execresult
DELETE FROM services
`

func (q *Queries) WipeServices(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, wipeServices)
}

const wipeSettings = `-- name: WipeSettings :execresult
DELETE FROM settings
`

func (q *Queries) WipeSettings(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, wipeSettings)
}
