// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rewrites.sql

package storedb

import (
	"context"
)

const deleteRewrite = `-- name: DeleteRewrite :exec
DELETE FROM rewrites WHERE domain = ?
`

func (q *Queries) DeleteRewrite(ctx context.Context, domain string) error {
	_, err := q.db.ExecContext(ctx, deleteRewrite, domain)
	return err
}

const listRewrites = `-- name: ListRewrites :many
SELECT domain, target
FROM rewrites ORDER BY domain
`

func (q *Queries) ListRewrites(ctx context.Context) ([]Rewrite, error) {
	rows, err := q.db.QueryContext(ctx, listRewrites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rewrite
	for rows.Next() {
		var i Rewrite
		if err := rows.Scan(&i.Domain, &i.Target); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveRewrite = `-- name: SaveRewrite :one
INSERT INTO rewrites (domain, target)
VALUES (?, ?)
ON CONFLICT (domain) DO UPDATE SET target = excluded.target
RETURNING domain
`

type SaveRewriteParams struct {
	Domain string
	Target string
}

func (q *Queries) SaveRewrite(ctx context.Context, arg SaveRewriteParams) (string, error) {
	row := q.db.QueryRowContext(ctx, saveRewrite, arg.Domain, arg.Target)
	var domain string
	err := row.Scan(&domain)
	return domain, err
}
