// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routes.sql

package storedb

import (
	"context"
)

const deleteRoute = `-- name: DeleteRoute :exec
DELETE FROM routes WHERE id = ?
`

func (q *Queries) DeleteRoute(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRoute, id)
	return err
}

const insertRoute = `-- name: InsertRoute :one
INSERT INTO routes (domain, client, upstream) VALUES (?, ?, ?)
RETURNING id
`

type InsertRouteParams struct {
	Domain   string
	Client   string
	Upstream string
}

func (q *Queries) InsertRoute(ctx context.Context, arg InsertRouteParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRoute, arg.Domain, arg.Client, arg.Upstream)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listRoutes = `-- name: ListRoutes :many
SELECT id, domain, client, upstream FROM routes ORDER BY id
`

func (q *Queries) ListRoutes(ctx context.Context) ([]Route, error) {
	rows, err := q.db.QueryContext(ctx, listRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Client,
			&i.Upstream,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoute = `-- name: UpdateRoute :exec
UPDATE routes
SET domain = ?, client = ?, upstream = ?
WHERE id = ?
`

type UpdateRouteParams struct {
	Domain   string
	Client   string
	Upstream string
	ID       int64
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) error {
	_, err := q.db.ExecContext(ctx, updateRoute,
		arg.Domain,
		arg.Client,
		arg.Upstream,
		arg.ID,
	)
	return err
}
