// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rules.sql

package storedb

import (
	"context"
)

const deleteRule = `-- name: DeleteRule :execrows
DELETE FROM rules WHERE id = ?
`

func (q *Queries) DeleteRule(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertRule = `-- name: InsertRule :one
INSERT INTO rules (domain, kind, action, notes, created, schedule, client)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertRuleParams struct {
	Domain   string
	Kind     string
	Action   string
	Notes    string
	Created  int64
	Schedule string
	Client   string
}

func (q *Queries) InsertRule(ctx context.Context, arg InsertRuleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRule,
		arg.Domain,
		arg.Kind,
		arg.Action,
		arg.Notes,
		arg.Created,
		arg.Schedule,
		arg.Client,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listRules = `-- name: ListRules :many
SELECT id, domain, kind, action, notes, created, schedule, client
FROM rules ORDER BY id
`

func (q *Queries) ListRules(ctx context.Context) ([]Rule, error) {
	rows, err := q.db.QueryContext(ctx, listRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Kind,
			&i.Action,
			&i.Notes,
			&i.Created,
			&i.Schedule,
			&i.Client,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ruleByID = `-- name: RuleByID :one
SELECT id, domain, kind, action, notes, created, schedule, client
FROM rules WHERE id = ?
`

func (q *Queries) RuleByID(ctx context.Context, id int64) (Rule, error) {
	row := q.db.QueryRowContext(ctx, ruleByID, id)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Kind,
		&i.Action,
		&i.Notes,
		&i.Created,
		&i.Schedule,
		&i.Client,
	)
	return i, err
}

const updateRule = `-- name: UpdateRule :exec
UPDATE rules
SET domain = ?, kind = ?, action = ?, notes = ?, created = ?, schedule = ?, client = ?
WHERE id = ?
`

type UpdateRuleParams struct {
	Domain   string
	Kind     string
	Action   string
	Notes    string
	Created  int64
	Schedule string
	Client   string
	ID       int64
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) error {
	_, err := q.db.ExecContext(ctx, updateRule,
		arg.Domain,
		arg.Kind,
		arg.Action,
		arg.Notes,
		arg.Created,
		arg.Schedule,
		arg.Client,
		arg.ID,
	)
	return err
}
