// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rules.sql

package storedb

import (
	"context"
)

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM rules WHERE id = ?
`

func (q *Queries) DeleteRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRule, id)
	return err
}

const insertRule = `-- name: InsertRule :one
INSERT INTO rules (domain, kind, action, notes, created)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type InsertRuleParams struct {
	Domain  string
	Kind    string
	Action  string
	Notes   string
	Created int64
}

func (q *Queries) InsertRule(ctx context.Context, arg InsertRuleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRule,
		arg.Domain,
		arg.Kind,
		arg.Action,
		arg.Notes,
		arg.Created,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listRules = `-- name: ListRules :many
SELECT id, domain, kind, action, notes, created
FROM rules ORDER BY id
`

func (q *Queries) ListRules(ctx context.Context) ([]Rule, error) {
	rows, err := q.db.QueryContext(ctx, listRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Kind,
			&i.Action,
			&i.Notes,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRule = `-- name: UpdateRule :exec
UPDATE rules
SET domain = ?, kind = ?, action = ?, notes = ?, created = ?
WHERE id = ?
`

type UpdateRuleParams struct {
	Domain  string
	Kind    string
	Action  string
	Notes   string
	Created int64
	ID      int64
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) error {
	_, err := q.db.ExecContext(ctx, updateRule,
		arg.Domain,
		arg.Kind,
		arg.Action,
		arg.Notes,
		arg.Created,
		arg.ID,
	)
	return err
}
