// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: safesearch.sql

package storedb

import (
	"context"
)

const deleteProfileSafesearch = `-- name: DeleteProfileSafesearch :exec
DELETE FROM profile_safesearch WHERE profile = ?
`

func (q *Queries) DeleteProfileSafesearch(ctx context.Context, profile string) error {
	_, err := q.db.ExecContext(ctx, deleteProfileSafesearch, profile)
	return err
}

const insertProfileSafesearch = `-- name: InsertProfileSafesearch :exec
INSERT INTO profile_safesearch (profile, engine) VALUES (?, ?)
`

type InsertProfileSafesearchParams struct {
	Profile string
	Engine  string
}

func (q *Queries) InsertProfileSafesearch(ctx context.Context, arg InsertProfileSafesearchParams) error {
	_, err := q.db.ExecContext(ctx, insertProfileSafesearch, arg.Profile, arg.Engine)
	return err
}

const listProfileSafesearch = `-- name: ListProfileSafesearch :many
SELECT profile, engine FROM profile_safesearch ORDER BY profile, engine
`

func (q *Queries) ListProfileSafesearch(ctx context.Context) ([]ProfileSafesearch, error) {
	rows, err := q.db.QueryContext(ctx, listProfileSafesearch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProfileSafesearch
	for rows.Next() {
		var i ProfileSafesearch
		if err := rows.Scan(&i.Profile, &i.Engine); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
