// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedules.sql

package storedb

import (
	"context"
)

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules WHERE name = ?
`

func (q *Queries) DeleteSchedule(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteSchedule, name)
	return err
}

const listSchedules = `-- name: ListSchedules :many
SELECT name, priority, windows
FROM schedules ORDER BY name
`

func (q *Queries) ListSchedules(ctx context.Context) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(&i.Name, &i.Priority, &i.Windows); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveSchedule = `-- name: SaveSchedule :one
INSERT INTO schedules (name, priority, windows)
VALUES (?, ?, ?)
ON CONFLICT (name) DO UPDATE SET priority = excluded.priority, windows = excluded.windows
RETURNING name
`

type SaveScheduleParams struct {
	Name     string
	Priority int64
	Windows  string
}

func (q *Queries) SaveSchedule(ctx context.Context, arg SaveScheduleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, saveSchedule, arg.Name, arg.Priority, arg.Windows)
	var name string
	err := row.Scan(&name)
	return name, err
}
