// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package storedb

import (
	"context"
)

const deleteClientServices = `-- name: DeleteClientServices :exec
DELETE FROM client_services WHERE client = ?
`

func (q *Queries) DeleteClientServices(ctx context.Context, client string) error {
	_, err := q.db.ExecContext(ctx, deleteClientServices, client)
	return err
}

const deleteProfileServices = `-- name: DeleteProfileServices :exec
DELETE FROM profile_services WHERE profile = ?
`

func (q *Queries) DeleteProfileServices(ctx context.Context, profile string) error {
	_, err := q.db.ExecContext(ctx, deleteProfileServices, profile)
	return err
}

const deleteServiceWindow = `-- name: DeleteServiceWindow :exec
DELETE FROM service_windows WHERE name = ?
`

func (q *Queries) DeleteServiceWindow(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteServiceWindow, name)
	return err
}

const insertClientService = `-- name: InsertClientService :exec
INSERT INTO client_services (client, service) VALUES (?, ?)
`

type InsertClientServiceParams struct {
	Client  string
	Service string
}

func (q *Queries) InsertClientService(ctx context.Context, arg InsertClientServiceParams) error {
	_, err := q.db.ExecContext(ctx, insertClientService, arg.Client, arg.Service)
	return err
}

const insertProfileService = `-- name: InsertProfileService :exec
INSERT INTO profile_services (profile, service) VALUES (?, ?)
`

type InsertProfileServiceParams struct {
	Profile string
	Service string
}

func (q *Queries) InsertProfileService(ctx context.Context, arg InsertProfileServiceParams) error {
	_, err := q.db.ExecContext(ctx, insertProfileService, arg.Profile, arg.Service)
	return err
}

const listClientServices = `-- name: ListClientServices :many
SELECT client, service FROM client_services ORDER BY client, service
`

func (q *Queries) ListClientServices(ctx context.Context) ([]ClientService, error) {
	rows, err := q.db.QueryContext(ctx, listClientServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientService
	for rows.Next() {
		var i ClientService
		if err := rows.Scan(&i.Client, &i.Service); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileServices = `-- name: ListProfileServices :many
SELECT profile, service FROM profile_services ORDER BY profile, service
`

func (q *Queries) ListProfileServices(ctx context.Context) ([]ProfileService, error) {
	rows, err := q.db.QueryContext(ctx, listProfileServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProfileService
	for rows.Next() {
		var i ProfileService
		if err := rows.Scan(&i.Profile, &i.Service); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceWindows = `-- name: ListServiceWindows :many
SELECT id, name, schedule, action, clients, services
FROM service_windows ORDER BY name
`

type ListServiceWindowsRow struct {
	ID       int64
	Name     string
	Schedule string
	Action   string
	Clients  string
	Services string
}

func (q *Queries) ListServiceWindows(ctx context.Context) ([]ListServiceWindowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listServiceWindows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServiceWindowsRow
	for rows.Next() {
		var i ListServiceWindowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Schedule,
			&i.Action,
			&i.Clients,
			&i.Services,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT id, name, group_name, rules, icon_svg, fetched_at FROM services ORDER BY id
`

type ListServicesRow struct {
	ID        string
	Name      string
	GroupName string
	Rules     string
	IconSvg   string
	FetchedAt int64
}

func (q *Queries) ListServices(ctx context.Context) ([]ListServicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServicesRow
	for rows.Next() {
		var i ListServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GroupName,
			&i.Rules,
			&i.IconSvg,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesForClient = `-- name: ListServicesForClient :many
SELECT service FROM client_services WHERE client = ? ORDER BY service
`

func (q *Queries) ListServicesForClient(ctx context.Context, client string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listServicesForClient, client)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var service string
		if err := rows.Scan(&service); err != nil {
			return nil, err
		}
		items = append(items, service)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesForProfile = `-- name: ListServicesForProfile :many
SELECT service FROM profile_services WHERE profile = ? ORDER BY service
`

func (q *Queries) ListServicesForProfile(ctx context.Context, profile string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listServicesForProfile, profile)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var service string
		if err := rows.Scan(&service); err != nil {
			return nil, err
		}
		items = append(items, service)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveServiceWindow = `-- name: SaveServiceWindow :one
INSERT INTO service_windows (name, schedule, action, clients, services)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (name) DO UPDATE SET
    schedule = excluded.schedule,
    action   = excluded.action,
    clients  = excluded.clients,
    services = excluded.services
RETURNING id
`

type SaveServiceWindowParams struct {
	Name     string
	Schedule string
	Action   string
	Clients  string
	Services string
}

func (q *Queries) SaveServiceWindow(ctx context.Context, arg SaveServiceWindowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, saveServiceWindow,
		arg.Name,
		arg.Schedule,
		arg.Action,
		arg.Clients,
		arg.Services,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const serviceWindowByName = `-- name: ServiceWindowByName :one
SELECT id, name, schedule, action, clients, services
FROM service_windows WHERE name = ?
`

type ServiceWindowByNameRow struct {
	ID       int64
	Name     string
	Schedule string
	Action   string
	Clients  string
	Services string
}

func (q *Queries) ServiceWindowByName(ctx context.Context, name string) (ServiceWindowByNameRow, error) {
	row := q.db.QueryRowContext(ctx, serviceWindowByName, name)
	var i ServiceWindowByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Schedule,
		&i.Action,
		&i.Clients,
		&i.Services,
	)
	return i, err
}

const upsertService = `-- name: UpsertService :exec
INSERT INTO services (id, name, group_name, rules, icon_svg, fetched_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    name = excluded.name,
    group_name = excluded.group_name,
    rules = excluded.rules,
    icon_svg = excluded.icon_svg,
    fetched_at = excluded.fetched_at
`

type UpsertServiceParams struct {
	ID        string
	Name      string
	GroupName string
	Rules     string
	IconSvg   string
	FetchedAt int64
}

func (q *Queries) UpsertService(ctx context.Context, arg UpsertServiceParams) error {
	_, err := q.db.ExecContext(ctx, upsertService,
		arg.ID,
		arg.Name,
		arg.GroupName,
		arg.Rules,
		arg.IconSvg,
		arg.FetchedAt,
	)
	return err
}
