// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package storedb

import (
	"context"
)

const deleteProfileServices = `-- name: DeleteProfileServices :exec
DELETE FROM profile_services WHERE profile = ?
`

func (q *Queries) DeleteProfileServices(ctx context.Context, profile string) error {
	_, err := q.db.ExecContext(ctx, deleteProfileServices, profile)
	return err
}

const insertProfileService = `-- name: InsertProfileService :exec
INSERT INTO profile_services (profile, service) VALUES (?, ?)
`

type InsertProfileServiceParams struct {
	Profile string
	Service string
}

func (q *Queries) InsertProfileService(ctx context.Context, arg InsertProfileServiceParams) error {
	_, err := q.db.ExecContext(ctx, insertProfileService, arg.Profile, arg.Service)
	return err
}

const listProfileServices = `-- name: ListProfileServices :many
SELECT profile, service FROM profile_services ORDER BY profile, service
`

func (q *Queries) ListProfileServices(ctx context.Context) ([]ProfileService, error) {
	rows, err := q.db.QueryContext(ctx, listProfileServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProfileService
	for rows.Next() {
		var i ProfileService
		if err := rows.Scan(&i.Profile, &i.Service); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT id, name, group_name, rules, fetched_at FROM services ORDER BY id
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GroupName,
			&i.Rules,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesForProfile = `-- name: ListServicesForProfile :many
SELECT service FROM profile_services WHERE profile = ? ORDER BY service
`

func (q *Queries) ListServicesForProfile(ctx context.Context, profile string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listServicesForProfile, profile)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var service string
		if err := rows.Scan(&service); err != nil {
			return nil, err
		}
		items = append(items, service)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertService = `-- name: UpsertService :exec
INSERT INTO services (id, name, group_name, rules, fetched_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    name = excluded.name,
    group_name = excluded.group_name,
    rules = excluded.rules,
    fetched_at = excluded.fetched_at
`

type UpsertServiceParams struct {
	ID        string
	Name      string
	GroupName string
	Rules     string
	FetchedAt int64
}

func (q *Queries) UpsertService(ctx context.Context, arg UpsertServiceParams) error {
	_, err := q.db.ExecContext(ctx, upsertService,
		arg.ID,
		arg.Name,
		arg.GroupName,
		arg.Rules,
		arg.FetchedAt,
	)
	return err
}
