// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources.sql

package storedb

import (
	"context"
)

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources WHERE name = ?
`

func (q *Queries) DeleteSource(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteSource, name)
	return err
}

const listEnabledSources = `-- name: ListEnabledSources :many
SELECT name, url, format, enabled, etag, last_fetch, last_error, rule_count, body
FROM sources WHERE enabled = 1 ORDER BY name
`

func (q *Queries) ListEnabledSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.Name,
			&i.Url,
			&i.Format,
			&i.Enabled,
			&i.Etag,
			&i.LastFetch,
			&i.LastError,
			&i.RuleCount,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT name, url, format, enabled, etag, last_fetch, last_error, rule_count, body
FROM sources ORDER BY name
`

func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.Name,
			&i.Url,
			&i.Format,
			&i.Enabled,
			&i.Etag,
			&i.LastFetch,
			&i.LastError,
			&i.RuleCount,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSourceFetch = `-- name: RecordSourceFetch :exec
UPDATE sources
SET etag = ?, last_fetch = ?, last_error = ?, rule_count = ?, body = ?
WHERE name = ?
`

type RecordSourceFetchParams struct {
	Etag      string
	LastFetch int64
	LastError string
	RuleCount int64
	Body      []byte
	Name      string
}

func (q *Queries) RecordSourceFetch(ctx context.Context, arg RecordSourceFetchParams) error {
	_, err := q.db.ExecContext(ctx, recordSourceFetch,
		arg.Etag,
		arg.LastFetch,
		arg.LastError,
		arg.RuleCount,
		arg.Body,
		arg.Name,
	)
	return err
}

const upsertSource = `-- name: UpsertSource :exec
INSERT INTO sources (name, url, format, enabled) VALUES (?, ?, ?, ?)
ON CONFLICT (name) DO UPDATE SET
    url = excluded.url,
    format = excluded.format,
    enabled = excluded.enabled
`

type UpsertSourceParams struct {
	Name    string
	Url     string
	Format  string
	Enabled int64
}

func (q *Queries) UpsertSource(ctx context.Context, arg UpsertSourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertSource,
		arg.Name,
		arg.Url,
		arg.Format,
		arg.Enabled,
	)
	return err
}
