// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources.sql

package storedb

import (
	"context"
)

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources WHERE name = ?
`

func (q *Queries) DeleteSource(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteSource, name)
	return err
}

const listEnabledSources = `-- name: ListEnabledSources :many
SELECT name, url, format, enabled, etag, last_fetch, last_error, rule_count, skipped, failures, refresh_seconds, body
FROM sources WHERE enabled = 1 ORDER BY name
`

type ListEnabledSourcesRow struct {
	Name           string
	Url            string
	Format         string
	Enabled        int64
	Etag           string
	LastFetch      int64
	LastError      string
	RuleCount      int64
	Skipped        int64
	Failures       int64
	RefreshSeconds int64
	Body           []byte
}

func (q *Queries) ListEnabledSources(ctx context.Context) ([]ListEnabledSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledSourcesRow
	for rows.Next() {
		var i ListEnabledSourcesRow
		if err := rows.Scan(
			&i.Name,
			&i.Url,
			&i.Format,
			&i.Enabled,
			&i.Etag,
			&i.LastFetch,
			&i.LastError,
			&i.RuleCount,
			&i.Skipped,
			&i.Failures,
			&i.RefreshSeconds,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT name, url, format, enabled, etag, last_fetch, last_error, rule_count, skipped, failures, refresh_seconds, body
FROM sources ORDER BY name
`

type ListSourcesRow struct {
	Name           string
	Url            string
	Format         string
	Enabled        int64
	Etag           string
	LastFetch      int64
	LastError      string
	RuleCount      int64
	Skipped        int64
	Failures       int64
	RefreshSeconds int64
	Body           []byte
}

func (q *Queries) ListSources(ctx context.Context) ([]ListSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourcesRow
	for rows.Next() {
		var i ListSourcesRow
		if err := rows.Scan(
			&i.Name,
			&i.Url,
			&i.Format,
			&i.Enabled,
			&i.Etag,
			&i.LastFetch,
			&i.LastError,
			&i.RuleCount,
			&i.Skipped,
			&i.Failures,
			&i.RefreshSeconds,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSourceFetch = `-- name: RecordSourceFetch :exec
UPDATE sources
SET etag = ?1, last_fetch = ?2, last_error = ?3, rule_count = ?4,
    skipped = ?5, body = ?6,
    failures = CASE WHEN ?3 = '' THEN 0 ELSE failures + 1 END
WHERE name = ?7
`

type RecordSourceFetchParams struct {
	Etag      string
	LastFetch int64
	LastError string
	RuleCount int64
	Skipped   int64
	Body      []byte
	Name      string
}

func (q *Queries) RecordSourceFetch(ctx context.Context, arg RecordSourceFetchParams) error {
	_, err := q.db.ExecContext(ctx, recordSourceFetch,
		arg.Etag,
		arg.LastFetch,
		arg.LastError,
		arg.RuleCount,
		arg.Skipped,
		arg.Body,
		arg.Name,
	)
	return err
}

const sourceByName = `-- name: SourceByName :one
SELECT name, url, format, enabled, etag, last_fetch, last_error, rule_count, skipped, failures, refresh_seconds, body
FROM sources WHERE name = ?
`

type SourceByNameRow struct {
	Name           string
	Url            string
	Format         string
	Enabled        int64
	Etag           string
	LastFetch      int64
	LastError      string
	RuleCount      int64
	Skipped        int64
	Failures       int64
	RefreshSeconds int64
	Body           []byte
}

func (q *Queries) SourceByName(ctx context.Context, name string) (SourceByNameRow, error) {
	row := q.db.QueryRowContext(ctx, sourceByName, name)
	var i SourceByNameRow
	err := row.Scan(
		&i.Name,
		&i.Url,
		&i.Format,
		&i.Enabled,
		&i.Etag,
		&i.LastFetch,
		&i.LastError,
		&i.RuleCount,
		&i.Skipped,
		&i.Failures,
		&i.RefreshSeconds,
		&i.Body,
	)
	return i, err
}

const upsertSource = `-- name: UpsertSource :exec
INSERT INTO sources (name, url, format, enabled, refresh_seconds) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (name) DO UPDATE SET
    url = excluded.url,
    format = excluded.format,
    enabled = excluded.enabled,
    refresh_seconds = excluded.refresh_seconds
`

type UpsertSourceParams struct {
	Name           string
	Url            string
	Format         string
	Enabled        int64
	RefreshSeconds int64
}

func (q *Queries) UpsertSource(ctx context.Context, arg UpsertSourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertSource,
		arg.Name,
		arg.Url,
		arg.Format,
		arg.Enabled,
		arg.RefreshSeconds,
	)
	return err
}
