// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package storedb

import (
	"context"
)

const clearStatsIgnored = `-- name: ClearStatsIgnored :exec
DELETE FROM stats_ignored
`

func (q *Queries) ClearStatsIgnored(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearStatsIgnored)
	return err
}

const deleteStatsWindow = `-- name: DeleteStatsWindow :exec
DELETE FROM queries WHERE time >= ?
`

func (q *Queries) DeleteStatsWindow(ctx context.Context, time int64) error {
	_, err := q.db.ExecContext(ctx, deleteStatsWindow, time)
	return err
}

const insertStatsIgnoredName = `-- name: InsertStatsIgnoredName :exec
INSERT INTO stats_ignored (name) VALUES (?)
ON CONFLICT DO NOTHING
`

func (q *Queries) InsertStatsIgnoredName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, insertStatsIgnoredName, name)
	return err
}

const statsHourBuckets = `-- name: StatsHourBuckets :many
SELECT (time / 3600000) * 3600000 AS bucket,
       verdict,
       COUNT(*) AS count
FROM queries
WHERE time >= ? AND NOT EXISTS (
    SELECT 1 FROM stats_ignored g
    WHERE queries.name = g.name OR queries.name LIKE '%.' || g.name
)
GROUP BY bucket, verdict
`

type StatsHourBucketsRow struct {
	Bucket  int64
	Verdict string
	Count   int64
}

func (q *Queries) StatsHourBuckets(ctx context.Context, time int64) ([]StatsHourBucketsRow, error) {
	rows, err := q.db.QueryContext(ctx, statsHourBuckets, time)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsHourBucketsRow
	for rows.Next() {
		var i StatsHourBucketsRow
		if err := rows.Scan(&i.Bucket, &i.Verdict, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsIgnoredNames = `-- name: StatsIgnoredNames :many
SELECT name FROM stats_ignored ORDER BY name ASC
`

func (q *Queries) StatsIgnoredNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, statsIgnoredNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsTopBlockedNames = `-- name: StatsTopBlockedNames :many
SELECT name, COUNT(*) AS count FROM queries
WHERE time >= ? AND verdict = 'block' AND NOT EXISTS (
    SELECT 1 FROM stats_ignored g
    WHERE queries.name = g.name OR queries.name LIKE '%.' || g.name
)
GROUP BY name
ORDER BY count DESC, name ASC
LIMIT ?
`

type StatsTopBlockedNamesParams struct {
	Time  int64
	Limit int64
}

type StatsTopBlockedNamesRow struct {
	Name  string
	Count int64
}

func (q *Queries) StatsTopBlockedNames(ctx context.Context, arg StatsTopBlockedNamesParams) ([]StatsTopBlockedNamesRow, error) {
	rows, err := q.db.QueryContext(ctx, statsTopBlockedNames, arg.Time, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsTopBlockedNamesRow
	for rows.Next() {
		var i StatsTopBlockedNamesRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsTopClients = `-- name: StatsTopClients :many
SELECT client, COUNT(*) AS count FROM queries
WHERE time >= ? AND NOT EXISTS (
    SELECT 1 FROM stats_ignored g
    WHERE queries.name = g.name OR queries.name LIKE '%.' || g.name
)
GROUP BY client
ORDER BY count DESC, client ASC
LIMIT ?
`

type StatsTopClientsParams struct {
	Time  int64
	Limit int64
}

type StatsTopClientsRow struct {
	Client string
	Count  int64
}

func (q *Queries) StatsTopClients(ctx context.Context, arg StatsTopClientsParams) ([]StatsTopClientsRow, error) {
	rows, err := q.db.QueryContext(ctx, statsTopClients, arg.Time, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsTopClientsRow
	for rows.Next() {
		var i StatsTopClientsRow
		if err := rows.Scan(&i.Client, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsTopNames = `-- name: StatsTopNames :many
SELECT name, COUNT(*) AS count FROM queries
WHERE time >= ? AND NOT EXISTS (
    SELECT 1 FROM stats_ignored g
    WHERE queries.name = g.name OR queries.name LIKE '%.' || g.name
)
GROUP BY name
ORDER BY count DESC, name ASC
LIMIT ?
`

type StatsTopNamesParams struct {
	Time  int64
	Limit int64
}

type StatsTopNamesRow struct {
	Name  string
	Count int64
}

func (q *Queries) StatsTopNames(ctx context.Context, arg StatsTopNamesParams) ([]StatsTopNamesRow, error) {
	rows, err := q.db.QueryContext(ctx, statsTopNames, arg.Time, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsTopNamesRow
	for rows.Next() {
		var i StatsTopNamesRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsVerdictTotals = `-- name: StatsVerdictTotals :many
SELECT verdict, COUNT(*) AS count FROM queries
WHERE time >= ? AND NOT EXISTS (
    SELECT 1 FROM stats_ignored g
    WHERE queries.name = g.name OR queries.name LIKE '%.' || g.name
)
GROUP BY verdict
`

type StatsVerdictTotalsRow struct {
	Verdict string
	Count   int64
}

func (q *Queries) StatsVerdictTotals(ctx context.Context, time int64) ([]StatsVerdictTotalsRow, error) {
	rows, err := q.db.QueryContext(ctx, statsVerdictTotals, time)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsVerdictTotalsRow
	for rows.Next() {
		var i StatsVerdictTotalsRow
		if err := rows.Scan(&i.Verdict, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trimQueriesBefore = `-- name: TrimQueriesBefore :exec
DELETE FROM queries WHERE time < ?
`

func (q *Queries) TrimQueriesBefore(ctx context.Context, time int64) error {
	_, err := q.db.ExecContext(ctx, trimQueriesBefore, time)
	return err
}
