// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: threats.sql

package storedb

import (
	"context"
)

const deleteThreatFeed = `-- name: DeleteThreatFeed :exec
DELETE FROM threat_feeds WHERE name = ?
`

func (q *Queries) DeleteThreatFeed(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteThreatFeed, name)
	return err
}

const insertThreatDomain = `-- name: InsertThreatDomain :exec
INSERT INTO threat_domains (domain, kind, feed)
VALUES (?, ?, ?)
ON CONFLICT (domain, feed) DO UPDATE SET kind = excluded.kind
`

type InsertThreatDomainParams struct {
	Domain string
	Kind   string
	Feed   string
}

func (q *Queries) InsertThreatDomain(ctx context.Context, arg InsertThreatDomainParams) error {
	_, err := q.db.ExecContext(ctx, insertThreatDomain, arg.Domain, arg.Kind, arg.Feed)
	return err
}

const insertThreatFinding = `-- name: InsertThreatFinding :exec
INSERT INTO threat_findings (time, client, kind, summary, evidence)
VALUES (?, ?, ?, ?, ?)
`

type InsertThreatFindingParams struct {
	Time     int64
	Client   string
	Kind     string
	Summary  string
	Evidence string
}

func (q *Queries) InsertThreatFinding(ctx context.Context, arg InsertThreatFindingParams) error {
	_, err := q.db.ExecContext(ctx, insertThreatFinding,
		arg.Time,
		arg.Client,
		arg.Kind,
		arg.Summary,
		arg.Evidence,
	)
	return err
}

const listThreatDomains = `-- name: ListThreatDomains :many
SELECT domain, kind, feed FROM threat_domains
`

func (q *Queries) ListThreatDomains(ctx context.Context) ([]ThreatDomain, error) {
	rows, err := q.db.QueryContext(ctx, listThreatDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThreatDomain
	for rows.Next() {
		var i ThreatDomain
		if err := rows.Scan(&i.Domain, &i.Kind, &i.Feed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreatFeeds = `-- name: ListThreatFeeds :many
SELECT name, url, enabled FROM threat_feeds ORDER BY name
`

func (q *Queries) ListThreatFeeds(ctx context.Context) ([]ThreatFeed, error) {
	rows, err := q.db.QueryContext(ctx, listThreatFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThreatFeed
	for rows.Next() {
		var i ThreatFeed
		if err := rows.Scan(&i.Name, &i.Url, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreatFindings = `-- name: ListThreatFindings :many
SELECT id, time, client, kind, summary, evidence
FROM threat_findings
ORDER BY id DESC
LIMIT ?1
`

func (q *Queries) ListThreatFindings(ctx context.Context, limit int64) ([]ThreatFinding, error) {
	rows, err := q.db.QueryContext(ctx, listThreatFindings, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThreatFinding
	for rows.Next() {
		var i ThreatFinding
		if err := rows.Scan(
			&i.ID,
			&i.Time,
			&i.Client,
			&i.Kind,
			&i.Summary,
			&i.Evidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceThreatDomains = `-- name: ReplaceThreatDomains :exec
DELETE FROM threat_domains WHERE feed = ?
`

func (q *Queries) ReplaceThreatDomains(ctx context.Context, feed string) error {
	_, err := q.db.ExecContext(ctx, replaceThreatDomains, feed)
	return err
}

const trimThreatFindings = `-- name: TrimThreatFindings :exec
DELETE FROM threat_findings WHERE id <= (
    SELECT id FROM threat_findings ORDER BY id DESC LIMIT 1 OFFSET ?1
)
`

func (q *Queries) TrimThreatFindings(ctx context.Context, keep int64) error {
	_, err := q.db.ExecContext(ctx, trimThreatFindings, keep)
	return err
}

const upsertThreatFeed = `-- name: UpsertThreatFeed :exec
INSERT INTO threat_feeds (name, url, enabled)
VALUES (?, ?, ?)
ON CONFLICT (name) DO UPDATE SET url = excluded.url, enabled = excluded.enabled
`

type UpsertThreatFeedParams struct {
	Name    string
	Url     string
	Enabled int64
}

func (q *Queries) UpsertThreatFeed(ctx context.Context, arg UpsertThreatFeedParams) error {
	_, err := q.db.ExecContext(ctx, upsertThreatFeed, arg.Name, arg.Url, arg.Enabled)
	return err
}
