// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upstreams.sql

package storedb

import (
	"context"
)

const deleteUpstream = `-- name: DeleteUpstream :exec
DELETE FROM upstreams WHERE name = ?
`

func (q *Queries) DeleteUpstream(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteUpstream, name)
	return err
}

const listUpstreams = `-- name: ListUpstreams :many
SELECT name, url, enabled, backup FROM upstreams ORDER BY name
`

func (q *Queries) ListUpstreams(ctx context.Context) ([]Upstream, error) {
	rows, err := q.db.QueryContext(ctx, listUpstreams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Upstream
	for rows.Next() {
		var i Upstream
		if err := rows.Scan(
			&i.Name,
			&i.Url,
			&i.Enabled,
			&i.Backup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUpstream = `-- name: UpsertUpstream :exec
INSERT INTO upstreams (name, url, enabled, backup) VALUES (?, ?, ?, ?)
ON CONFLICT (name) DO UPDATE SET
    url = excluded.url,
    enabled = excluded.enabled,
    backup = excluded.backup
`

type UpsertUpstreamParams struct {
	Name    string
	Url     string
	Enabled int64
	Backup  int64
}

func (q *Queries) UpsertUpstream(ctx context.Context, arg UpsertUpstreamParams) error {
	_, err := q.db.ExecContext(ctx, upsertUpstream,
		arg.Name,
		arg.Url,
		arg.Enabled,
		arg.Backup,
	)
	return err
}
